apiVersion: v1
kind: ConfigMap
metadata:
  name: example-secret
data:
  mydata: <prod/secret:foo | jsonParse | jsonPath {.browsers.firefox['pref\.url']}>
  db-name: <non-prod/rds:stage | jsonParse | jsonPath {.username}>
  db-pass: <non-prod/rds:stage | jsonParse | jsonPath {.password}>
  spring.profiles.active: rod
