apiVersion: v1
kind: ConfigMap
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: prod/secret
data:
  mydata: <foo | jsonParse | jsonPath {.browsers.firefox['pref\.url']}>
  spring.profiles.active: rod
