apiVersion: v1
kind: ConfigMap
metadata:
  name: example-secret
#  annotations:
#    avp.kubernetes.io/path: prod/secret
data:
  # mydata: <foo | jsonParse | jsonPath {.browsers.firefox['pref\.url']}>
  mydata: <prod/secret:prod/secret#foo | jsonParse | jsonPath {.browsers.firefox['pref\.url']}>
  db-name: <non-prod/rds:non-prod/rds#stage | jsonParse | jsonPath {.username}>
  db-pass: <non-prod/rds:#stage | jsonParse | jsonPath {.password}>
  spring.profiles.active: rod
